services:
  server:
    build:
      context: ./server
    container_name: remote-script-engine-server
    ports:
      - "8807:8807"

  client:
    build:
      context: ./client
    environment:
      - SERVER_HOST=server
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
